//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        public ItemCategory()
        {
            this.Item = new HashSet<Item>();
        }
    
        public System.Guid Id { get; set; }
        public string Names { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
